[pytest]
minversion = 7.0
testpaths = tests
addopts = -ra -v --strict-markers
filterwarnings =
    ignore::DeprecationWarning
python_files = test_*.py
python_classes = Test*
python_functions = test_*
